services:
#  app:
#    build: .
#    container_name: spring-app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#    networks:
#      - my-network
#
  mysql:
    image: mysql:8.0.38
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: redis-db
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
